spring.application.name=demo
server.port=4040
error-reporter.endpoint= http://localhost:5000/logs
error-reporter.service-name= order-service
error-reporter.environment= prod
error-reporter.enabled= true
